/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;


import Database.Mysql;
import Model.Product;
import View.Login;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.awt.Font;
import java.awt.Image;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import java.sql.*;
import java.util.List;
import java.util.Vector;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MSI GF63 11UC
 */
public class HomeNhanVien extends javax.swing.JFrame {

    /**
     * Creates new form Home1
     */
    public HomeNhanVien() {
        initComponents();
//        loadtotable();
        loadtobill();
    }
     // width 210 heigth 600
    int width =125;
    int height = 610;
    //phương thức mở menu
     private void openMenuBar() {
        // tạo luồng chạy song song với luông chính main
        new Thread(new Runnable(){
            @Override
            public void run() {
               for(int i =0 ;i <= width;i++){
                   pnMenu.setSize(i, height);
                   try {
                       //mở từ từ
                       Thread.sleep(2);
                   } catch (InterruptedException ex) {
                       Logger.getLogger(HomeNhanVien.class.getName()).log(Level.SEVERE, null, ex);
                   }
               }
            }
            
        }).start();
    }
     //phương thức đóng menu
     private void closeMenuBar(){
     new Thread(new Runnable(){
            @Override
            public void run() {
               for(int i = width ;i>=0;i--){
                   pnMenu.setSize(i, height);
                    try {
                       //mở từ từ
                       Thread.sleep(2);
                   } catch (InterruptedException ex) {
                       Logger.getLogger(HomeNhanVien.class.getName()).log(Level.SEVERE, null, ex);
                   }
               }
            }
            
        }).start();
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
      
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnMain = new javax.swing.JPanel();
        pnMenu = new javax.swing.JPanel();
        lbTrangchu = new javax.swing.JLabel();
        lbBanhang = new javax.swing.JLabel();
        lbHoadon = new javax.swing.JLabel();
        lbSanpham = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbClose = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        lbOpen = new javax.swing.JLabel();
        pnContainer = new javax.swing.JPanel();
        Home = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        bill = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lbBILL = new javax.swing.JLabel();
        btnThanhtoan = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        sotien = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        billModel = new javax.swing.JTable();
        product = new javax.swing.JPanel();
        pnSanpham = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtmasp = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txttensp = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtgiasp = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        timkiem = new javax.swing.JButton();
        lbanh = new javax.swing.JLabel();
        btnAnh = new javax.swing.JButton();
        khungchuasp = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbModel = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnMain.setBackground(new java.awt.Color(255, 204, 153));

        pnMenu.setBackground(new java.awt.Color(204, 102, 0));
        pnMenu.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnMenu.setPreferredSize(new java.awt.Dimension(120, 310));

        lbTrangchu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbTrangchu.setForeground(new java.awt.Color(255, 255, 255));
        lbTrangchu.setText("Trang chủ");
        lbTrangchu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbTrangchuMouseClicked(evt);
            }
        });

        lbBanhang.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbBanhang.setForeground(new java.awt.Color(255, 255, 255));
        lbBanhang.setText("Bán hàng");
        lbBanhang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbBanhangMouseClicked(evt);
            }
        });

        lbHoadon.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbHoadon.setForeground(new java.awt.Color(255, 255, 255));
        lbHoadon.setText("Hoá Đơn");
        lbHoadon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbHoadonMouseClicked(evt);
            }
        });

        lbSanpham.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbSanpham.setForeground(new java.awt.Color(255, 255, 255));
        lbSanpham.setText("Sản Phẩm ");
        lbSanpham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbSanphamMouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon/coffee-cup.png"))); // NOI18N

        lbClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon/icons8-close-30.png"))); // NOI18N
        lbClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbCloseMouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel9.setText("Coffe Chill");

        logout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon/power.png"))); // NOI18N
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnMenuLayout = new javax.swing.GroupLayout(pnMenu);
        pnMenu.setLayout(pnMenuLayout);
        pnMenuLayout.setHorizontalGroup(
            pnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbClose))
            .addGroup(pnMenuLayout.createSequentialGroup()
                .addGroup(pnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnMenuLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnMenuLayout.createSequentialGroup()
                        .addGroup(pnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnMenuLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnMenuLayout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(pnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbHoadon, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbTrangchu, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(lbSanpham, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                                        .addComponent(lbBanhang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnMenuLayout.setVerticalGroup(
            pnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMenuLayout.createSequentialGroup()
                .addComponent(lbClose)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel9))
                .addGap(70, 70, 70)
                .addComponent(lbTrangchu)
                .addGap(27, 27, 27)
                .addComponent(lbBanhang)
                .addGap(30, 30, 30)
                .addComponent(lbHoadon)
                .addGap(31, 31, 31)
                .addComponent(lbSanpham)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logout)
                .addGap(15, 15, 15))
        );

        lbOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon/munu 32.png"))); // NOI18N
        lbOpen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbOpenMouseClicked(evt);
            }
        });

        pnContainer.setLayout(new java.awt.CardLayout());

        Home.setBackground(new java.awt.Color(255, 245, 229));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon/coffee-shop (1).png"))); // NOI18N

        javax.swing.GroupLayout HomeLayout = new javax.swing.GroupLayout(Home);
        Home.setLayout(HomeLayout);
        HomeLayout.setHorizontalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeLayout.createSequentialGroup()
                .addGap(375, 375, 375)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        HomeLayout.setVerticalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeLayout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(210, Short.MAX_VALUE))
        );

        pnContainer.add(Home, "card2");

        lbBILL.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbBILL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbBILL.setText("Hóa Đơn");

        btnThanhtoan.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnThanhtoan.setForeground(new java.awt.Color(204, 0, 0));
        btnThanhtoan.setText("Thanh toán");
        btnThanhtoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhtoanActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel8.setText("Tổng hóa đơn:");

        sotien.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        sotien.setText("0");

        billModel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Giá"
            }
        ));
        billModel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                billModelMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(billModel);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout billLayout = new javax.swing.GroupLayout(bill);
        bill.setLayout(billLayout);
        billLayout.setHorizontalGroup(
            billLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, billLayout.createSequentialGroup()
                .addGap(397, 397, 397)
                .addComponent(lbBILL, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(billLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(billLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(billLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(223, 223, 223)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, billLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sotien, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnThanhtoan, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        billLayout.setVerticalGroup(
            billLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(billLayout.createSequentialGroup()
                .addGroup(billLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(billLayout.createSequentialGroup()
                        .addGap(389, 389, 389)
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(billLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(lbBILL, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(billLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThanhtoan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sotien, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );

        pnContainer.add(bill, "card4");

        pnSanpham.setBackground(new java.awt.Color(253, 153, 0));

        jLabel4.setText("Mã sản  phẩm");

        jLabel5.setText("Tên sản phẩm");

        txttensp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttenspActionPerformed(evt);
            }
        });

        jLabel6.setText("Giá sản phẩm");

        txtgiasp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtgiaspActionPerformed(evt);
            }
        });

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setText("Xoá");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        timkiem.setText("Tìm kiếm");
        timkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timkiemActionPerformed(evt);
            }
        });

        lbanh.setBackground(new java.awt.Color(255, 255, 255));

        btnAnh.setText("chọn ảnh");
        btnAnh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnhActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnSanphamLayout = new javax.swing.GroupLayout(pnSanpham);
        pnSanpham.setLayout(pnSanphamLayout);
        pnSanphamLayout.setHorizontalGroup(
            pnSanphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSanphamLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(pnSanphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtmasp, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addGroup(pnSanphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnAnh)
                        .addGroup(pnSanphamLayout.createSequentialGroup()
                            .addGroup(pnSanphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(pnSanphamLayout.createSequentialGroup()
                                    .addComponent(btnThem)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                                    .addComponent(btnSua))
                                .addComponent(txtgiasp, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txttensp, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(pnSanphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnSanphamLayout.createSequentialGroup()
                                    .addGap(126, 126, 126)
                                    .addComponent(timkiem))
                                .addGroup(pnSanphamLayout.createSequentialGroup()
                                    .addGap(62, 62, 62)
                                    .addGroup(pnSanphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbanh, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnXoa)))))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        pnSanphamLayout.setVerticalGroup(
            pnSanphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSanphamLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtmasp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(pnSanphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnSanphamLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txttensp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel6))
                    .addGroup(pnSanphamLayout.createSequentialGroup()
                        .addComponent(lbanh, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAnh)
                        .addGap(29, 29, 29)))
                .addGroup(pnSanphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnSanphamLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(timkiem))
                    .addGroup(pnSanphamLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtgiasp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnSanphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnSua)
                    .addComponent(btnXoa))
                .addGap(55, 55, 55))
        );

        khungchuasp.setBackground(new java.awt.Color(255, 255, 255));
        khungchuasp.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tbModel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MaSanPham", "TenSanPham", "GiaSanPham", "hinhanhsp"
            }
        ));
        tbModel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbModelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbModel);

        javax.swing.GroupLayout khungchuaspLayout = new javax.swing.GroupLayout(khungchuasp);
        khungchuasp.setLayout(khungchuaspLayout);
        khungchuaspLayout.setHorizontalGroup(
            khungchuaspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
        );
        khungchuaspLayout.setVerticalGroup(
            khungchuaspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout productLayout = new javax.swing.GroupLayout(product);
        product.setLayout(productLayout);
        productLayout.setHorizontalGroup(
            productLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnSanpham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(khungchuasp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        productLayout.setVerticalGroup(
            productLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnSanpham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(productLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(khungchuasp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnContainer.add(product, "card5");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Nhân Viên");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon/chat.png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnMainLayout = new javax.swing.GroupLayout(pnMain);
        pnMain.setLayout(pnMainLayout);
        pnMainLayout.setHorizontalGroup(
            pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMainLayout.createSequentialGroup()
                .addComponent(pnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnMainLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(lbOpen, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))))
        );
        pnMainLayout.setVerticalGroup(
            pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE)
            .addGroup(pnMainLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbOpen)
                    .addGroup(pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)))
                .addGap(18, 18, 18)
                .addComponent(pnContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnMenu.getAccessibleContext().setAccessibleName("");
        pnMenu.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        this.dispose();
        login.setVisible(true);
    }//GEN-LAST:event_logoutMouseClicked

    private void tbModelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbModelMouseClicked
//        // TODO add your handling code here:
//        int row = tbModel.getSelectedRow();
//        String MaSanPham = tbModel.getValueAt(row, 0).toString();
//        String TenSanPham = tbModel.getValueAt(row, 1).toString();
//        String GiaSanPham = tbModel.getValueAt(row, 2).toString();
//        String hinhanhsp = tbModel.getValueAt(row, 3).toString();
//
//        txtmasp.setText(MaSanPham);
//        txttensp.setText(TenSanPham);
//        txtgiasp.setText(GiaSanPham);
//        imagePath = hinhanhsp;
//
//        try {
//            File imgFile = new File(hinhanhsp);
//            if (imgFile.exists()) {
//                BufferedImage img = ImageIO.read(imgFile);
//                Image scaledImg = img.getScaledInstance(lbanh.getWidth(), lbanh.getHeight(), Image.SCALE_SMOOTH);
//                lbanh.setIcon(new ImageIcon(scaledImg));
//            } else {
//                JOptionPane.showMessageDialog(null, "Không tìm thấy tệp hình ảnh: " + hinhanhsp);
//            }
//        } catch (IOException ioException) {
//            JOptionPane.showMessageDialog(null, "Lỗi tải hình ảnh: " + ioException.getMessage());
//        }
//
//        // Cập nhật nhãn chuathongtinsp với thông tin sản phẩm

    }//GEN-LAST:event_tbModelMouseClicked

    private void btnAnhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnhActionPerformed
//        JFileChooser fileChooser = new JFileChooser();
//        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
//        fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Image files", "jpg", "jpeg", "png", "gif"));
//        int returnValue = fileChooser.showOpenDialog(null);
//        if (returnValue == JFileChooser.APPROVE_OPTION) {
//            File selectedFile = fileChooser.getSelectedFile();
//            imagePath = selectedFile.getAbsolutePath();
//            try {
//                BufferedImage img = ImageIO.read(selectedFile);
//                Image scaledImg = img.getScaledInstance(lbanh.getWidth(), lbanh.getHeight(), Image.SCALE_SMOOTH);
//                lbanh.setIcon(new ImageIcon(scaledImg));
//            } catch (IOException ioException) {
//                JOptionPane.showMessageDialog(null, "Lỗi tải hình ảnh: " + ioException.getMessage());
//            }
//        }

    }//GEN-LAST:event_btnAnhActionPerformed

    private void timkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timkiemActionPerformed
//        String maSanPham = txtmasp.getText();
//
//        try {
//            Connection conn = Mysql.getConnection();
//            String sql = "SELECT tenSanPham, giaSanPham, hinhanhsp FROM product WHERE maSanPham = ?";
//            PreparedStatement pstmt = conn.prepareStatement(sql);
//            pstmt.setString(1, maSanPham);
//            ResultSet rs = pstmt.executeQuery();
//
//            if (rs.next()) {
//                String tenSanPham = rs.getString("tenSanPham");
//                double giaSanPham = rs.getDouble("giaSanPham");
//                String hinhAnh = rs.getString("hinhanhsp");
//
//                txttensp.setText(tenSanPham);
//                txtgiasp.setText(String.valueOf(giaSanPham));
//                imagePath = hinhAnh;
//
//                try {
//                    File imgFile = new File(hinhAnh);
//                    if (imgFile.exists()) {
//                        BufferedImage img = ImageIO.read(imgFile);
//                        Image scaledImg = img.getScaledInstance(lbanh.getWidth(), lbanh.getHeight(), Image.SCALE_SMOOTH);
//                        lbanh.setIcon(new ImageIcon(scaledImg));
//                    } else {
//                        JOptionPane.showMessageDialog(null, "Không tìm thấy tệp hình ảnh: " + hinhAnh);
//                    }
//                } catch (IOException ioException) {
//                    JOptionPane.showMessageDialog(null, "Lỗi tải hình ảnh: " + ioException.getMessage());
//                }
//
//                // Cập nhật nhãn chuathongtinsp với thông tin sản phẩm
//
//            } else {
//                JOptionPane.showMessageDialog(null, "Không tìm thấy sản phẩm với mã: " + maSanPham);
//            }
//
//        } catch (SQLException ex) {
//            JOptionPane.showMessageDialog(null, "Lỗi: " + ex.getMessage());
//        }

    }//GEN-LAST:event_timkiemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
//        String maSanPham = txtmasp.getText();
//
//        try {
//            Connection conn = Mysql.getConnection();
//            String sql = "DELETE FROM product WHERE maSanPham = ?";
//            PreparedStatement pstmt = conn.prepareStatement(sql);
//            pstmt.setString(1, maSanPham);
//            int rowsDeleted = pstmt.executeUpdate();
//
//            if (rowsDeleted > 0) {
//                JOptionPane.showMessageDialog(null, "Xoá sản phẩm thành công");
//
//                txttensp.setText("");
//                txtgiasp.setText("");
//                lbanh.setIcon(null);
//                imagePath = null;
//            } else {
//                JOptionPane.showMessageDialog(null, "Không tìm thấy sản phẩm với mã: " + maSanPham);
//            }
//        } catch (SQLException ex) {
//            JOptionPane.showMessageDialog(null, "Lỗi: " + ex.getMessage());
//        }
//
//        Model = new DefaultTableModel(null,headers);
//        loadtotable();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
//        String maSanPham = txtmasp.getText();
//        String tenSanPham = txttensp.getText();
//        double giaSanPham = Double.parseDouble(txtgiasp.getText());
//
//        if (imagePath == null || imagePath.isEmpty()) {
//            JOptionPane.showMessageDialog(null, "Vui lòng tải lên ảnh sản phẩm");
//            return;
//        }
//
//        try {
//            Connection conn = Mysql.getConnection();
//            String sql = "UPDATE product SET tenSanPham = ?, giaSanPham = ?, hinhanhsp = ? WHERE maSanPham = ?";
//            PreparedStatement pstmt = conn.prepareStatement(sql);
//            pstmt.setString(1, tenSanPham);
//            pstmt.setDouble(2, giaSanPham);
//            pstmt.setString(3, imagePath);
//            pstmt.setString(4, maSanPham);
//            int rowsUpdated = pstmt.executeUpdate();
//
//            if (rowsUpdated > 0) {
//                JOptionPane.showMessageDialog(null, "Sửa thông tin sản phẩm thành công");
//            } else {
//                JOptionPane.showMessageDialog(null, "Không tìm thấy sản phẩm với mã: " + maSanPham);
//            }
//        } catch (SQLException ex) {
//            JOptionPane.showMessageDialog(null, "Lỗi: " + ex.getMessage());
//        }
//
//        Model = new DefaultTableModel(null,headers);
//        loadtotable();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
//        String maSanPham = txtmasp.getText();
//        String tenSanPham = txttensp.getText();
//        double giaSanPham = Double.parseDouble(txtgiasp.getText());
//
//        if (imagePath == null || imagePath.isEmpty()) {
//            JOptionPane.showMessageDialog(null, "Vui lòng tải lên ảnh sản phẩm");
//            return;
//        }
//
//        try {
//            Connection conn = Mysql.getConnection();
//            // Kiểm tra xem mã sản phẩm đã tồn tại chưa
//            String checkSQL = "SELECT * FROM product WHERE maSanPham = ?";
//            PreparedStatement checkStmt = conn.prepareStatement(checkSQL);
//            checkStmt.setString(1, maSanPham);
//            ResultSet rs = checkStmt.executeQuery();
//            if (rs.next()) {
//                JOptionPane.showMessageDialog(null, "Mã sản phẩm đã tồn tại. Vui lòng chọn mã sản phẩm khác.", "Lỗi", JOptionPane.ERROR_MESSAGE);
//                return; // Thoát khỏi phương thức nếu mã sản phẩm đã tồn tại
//            }
//
//            // Thêm sản phẩm mới nếu mã sản phẩm không tồn tại
//            String insertSQL = "INSERT INTO product (maSanPham, tenSanPham, giaSanPham, hinhanhsp) VALUES (?, ?, ?, ?)";
//            PreparedStatement pstmt = conn.prepareStatement(insertSQL);
//            pstmt.setString(1, maSanPham);
//            pstmt.setString(2, tenSanPham);
//            pstmt.setDouble(3, giaSanPham);
//            pstmt.setString(4, imagePath);
//            pstmt.executeUpdate();
//
//            JOptionPane.showMessageDialog(null, "Thêm sản phẩm thành công");
//        } catch (SQLException ex) {
//            JOptionPane.showMessageDialog(null, "Lỗi: " + ex.getMessage());
//        }
//
//        Model = new DefaultTableModel(null,headers);
//        loadtotable();
    }//GEN-LAST:event_btnThemActionPerformed

    private void txtgiaspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtgiaspActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtgiaspActionPerformed

    private void txttenspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttenspActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttenspActionPerformed

    private void billModelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_billModelMouseClicked
        int row = billModel.getSelectedRow();
        String masp = billModel.getValueAt(row, 0).toString();
        if(selectedProducts.contains(masp)){
            selectedProducts.remove(masp);
        }
        else{
            selectedProducts.add(masp);
        }
        double totalPrice=0.0;
        for(String selectedProduct : selectedProducts){
            for(int i =0;i<Model2.getRowCount();i++){
                if(selectedProduct.equals(Model2.getValueAt(i, 0).toString())){
                    double gia = Double.parseDouble(Model2.getValueAt(i, 2).toString());
                    totalPrice+=gia ;
                    break;
                }
            }
        }
        sotien.setText(String.valueOf(totalPrice)  + "đ" );

    }//GEN-LAST:event_billModelMouseClicked

    private void btnThanhtoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhtoanActionPerformed

        confirmPayment();

    }//GEN-LAST:event_btnThanhtoanActionPerformed

    private void lbOpenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbOpenMouseClicked
        openMenuBar();
    }//GEN-LAST:event_lbOpenMouseClicked

    private void lbCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCloseMouseClicked
        closeMenuBar();
    }//GEN-LAST:event_lbCloseMouseClicked

    private void lbSanphamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbSanphamMouseClicked
        product.setVisible(false);

    }//GEN-LAST:event_lbSanphamMouseClicked

    private void lbHoadonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbHoadonMouseClicked
        bill.setVisible(true);
        Home.setVisible(false);
        product.setVisible(false);

    }//GEN-LAST:event_lbHoadonMouseClicked

    private void lbBanhangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbBanhangMouseClicked

        new sell().setVisible(true);
        setVisible(false);
       
    }//GEN-LAST:event_lbBanhangMouseClicked

    private void lbTrangchuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbTrangchuMouseClicked
        Home.setVisible(true);
        bill.setVisible(false);
        product.setVisible(false);

    }//GEN-LAST:event_lbTrangchuMouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
         Chat_client ccl = new Chat_client();
         ccl.setVisible(true);
    }//GEN-LAST:event_jLabel10MouseClicked
    String imagePath;    
    
    
    public void confirmPayment(){
        int option = JOptionPane.showConfirmDialog(this,"Xác nhận thanh toán","Xác nhận",JOptionPane.YES_NO_OPTION);
        if(option == JOptionPane.YES_OPTION){
            JOptionPane.showMessageDialog(this," Thanh toán thành công!");
            
           
            for(int i = selectedProducts.size()-1;i>=0;i--){
                String masp = selectedProducts.get(i);
                for(int j=0;j<Model2.getRowCount();j++){
                    if(masp.equals(Model2.getValueAt(j, 0).toString())){
                        Model2.removeRow(j);
                        break;
                    }
                }
                 deleteSelectedItemDatabase();
            }
//            selectedProducts.clear();
            sotien.setText("0 đ");
        }
    }
    
    
    public void deleteSelectedItemDatabase(){
        try {
           Connection conn = Mysql.getConnection();
           for(String masp : selectedProducts){
               String sql = "DELETE FROM hoadon WHERE masp = ?";
               PreparedStatement pstm =  conn.prepareStatement(sql);
               pstm.setString(1, masp);
               pstm.executeUpdate();
           }
             
                  
                   
             
         } catch (Exception e) {
        }
    }
    private List<String> selectedProducts = new ArrayList<>();
      
    private static Login login = new Login();
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeNhanVien().setVisible(true);
            }
        
    });
    }
//     String[] headers ={"Ma San Pham","Ten San Pham","Gia San Pham","hinhanhsp"};
//     DefaultTableModel Model = new DefaultTableModel(null,headers);
//     
//     public void loadtotable(){
//         try {
//             PreparedStatement st = Mysql.connection.prepareStatement("Select * from product");
//             ResultSet rs = st.executeQuery();
//
//             while(rs.next()){
//                   Vector v = new Vector();
//                   v.add(rs.getString("maSanPham"));
//                   v.add(rs.getString("tenSanPham"));
//                   v.add(rs.getDouble("giaSanPham"));
//                   v.add(rs.getString("hinhanhsp"));
//                   Model.addRow(v);
//             }
//             tbModel.setModel(Model);
//         } catch (Exception e) {
//         }
//     }
      String[] header ={"Ma San Pham","Ten San Pham","Gia San Pham"};
     DefaultTableModel Model2 = new DefaultTableModel(null,header);
     public void loadtobill(){
         try {
             PreparedStatement st = Mysql.connection.prepareStatement("Select * from hoadon");
             ResultSet rs1 = st.executeQuery();
            
             
             while(rs1.next()){
                   String masp= rs1.getString("masp");
                   String tensp= rs1.getString("tensp");
                   double gia =rs1.getDouble("gia");
                   Model2.addRow(new Object[]{masp,tensp,gia});
             }
             
             billModel.setModel(Model2);
         } catch (Exception e) {
         }
     }
   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Home;
    private javax.swing.JPanel bill;
    private javax.swing.JTable billModel;
    private javax.swing.JButton btnAnh;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThanhtoan;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel khungchuasp;
    private javax.swing.JLabel lbBILL;
    private javax.swing.JLabel lbBanhang;
    private javax.swing.JLabel lbClose;
    private javax.swing.JLabel lbHoadon;
    private javax.swing.JLabel lbOpen;
    private javax.swing.JLabel lbSanpham;
    private javax.swing.JLabel lbTrangchu;
    private javax.swing.JLabel lbanh;
    private javax.swing.JLabel logout;
    private javax.swing.JPanel pnContainer;
    private javax.swing.JPanel pnMain;
    private javax.swing.JPanel pnMenu;
    private javax.swing.JPanel pnSanpham;
    private javax.swing.JPanel product;
    private javax.swing.JLabel sotien;
    private javax.swing.JTable tbModel;
    private javax.swing.JButton timkiem;
    private javax.swing.JTextField txtgiasp;
    private javax.swing.JTextField txtmasp;
    private javax.swing.JTextField txttensp;
    // End of variables declaration//GEN-END:variables
 
}
